version: '3.9'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - "DATABASE_URL=${DATABASE_URL}"
    depends_on:
      - "db"

  db:
    image: "postgres:15"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  postgres_data:
